
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Generados;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ERRORLEX = 7;
  public static final int NUMERO = 6;
  public static final int MAS = 2;
  public static final int error = 1;
  public static final int PC = 5;
  public static final int PA = 4;
  public static final int POR = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "POR",
  "PA",
  "PC",
  "NUMERO",
  "ERRORLEX"
  };
}

